"""
Explanation Agent

Explains the results
generated by tools.
"""

from config.llm import ask_llm


class ExplanationAgent:

    def explain(

        self,

        question,

        result
    ):

        prompt = f"""
You are an expert
Data Scientist.

Question:

{question}

Result:

{result}

Explain the result
professionally and
provide insights.
"""

        return ask_llm(
            prompt
        )


explanation_agent = (
    ExplanationAgent()
)